service: python-pillow-layers
frameworkVersion: ">=1.34.0 <2.0.0"

custom:
  default_stage: dev
  stage: ${opt:stage, self:custom.default_stage}
  region: us-east-1

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    REGION: ${self:custom.region}

layers:
  pillowPython36:
    path: layer
    description: A Layer to support PIL in Python 3.6 Lambda functions
    compatibleRuntimes:
      - python3.6
